### ISSUE TITLE
Why does createRelease.sh set JAVA_HOME?

### ISSUE THREAD

**Issue by fartdev** [Coffee-Client/Coffee#12]
This caused me a headache for a few minutes as I wondered why I wasn't able to run `createRelease.sh` even though my `JAVA_HOME` is correctly set. pls fix. 

https://github.com/Coffee-Client/Coffee/blob/914f0cf54dffc130194508fac22eac107df08132/createRelease.sh#L18

**Comment by 0x3C50** [comment]
idk
