### ISSUE TITLE
Client is fucked when I load in a singleplayer world

### ISSUE THREAD

**Issue by Savvakos7** [Coffee-Client/Coffee#13]
Firstly,no commands work, nothing spawns,the world is useless.And when I exit from the singleplayer world,the screen is stuck on "Saving World" and Minecraft isn't closing,I have to restart my PC for this to close

**Comment by RandomVersion** [comment]
dont use windows

**Comment by 0x3C50** [comment]
what mods do you have

**Comment by Savvakos7** [comment]
> what mods do you have

no mods,only the jar and the api

**Comment by 0x3C50** [comment]
send latest.log file

**Comment by 0x3C50** [comment]
Reopening when latest.log file is here, closing
