### ISSUE TITLE
Client is going  very wrong somewhere

### ISSUE THREAD

**Issue by Savvakos7** [Coffee-Client/Coffee#14]
I have deleted several times and each time I put it in my mods folder it saves my presets and automatically turns chunk crasher on and when I join a server with hubs basically it is boot looping,and this happens every time I open the client,it doesn't matter if I go to single player and turn it off.Also there is no way to open the GUI while in main menu.

**Comment by RandomVersion** [comment]
skill issue

**Comment by Savvakos7** [comment]
> skill issue

"Skill issue"-🤓

**Comment by RandomVersion** [comment]
@0x3C50 h

**Comment by 0x3C50** [comment]
stop client, delete .minecraft/coffee, restart
