### ISSUE TITLE
Killaura ctx shows decimals when reach enabled

### ISSUE THREAD

**Issue by fartdev** [Coffee-Client/Coffee#22]
### The long float displayed by Killaura context:

![long float](https://media.discordapp.net/attachments/904758037359759450/984275508172845076/unknown.png)

### Reach is enabled:

![reach enabled](https://media.discordapp.net/attachments/904758037359759450/984276003021000764/unknown.png)

**Comment by 0x3C50** [comment]
oh shit

**Comment by 0x3C50** [comment]
fixed, forgot to close
