### ISSUE TITLE
Alt Usage

### ISSUE THREAD

**Issue by blazejoski** [Coffee-Client/Coffee#25]
I tried using my alt account wich is Mojang and it said unknown when I typed everything right in the bar and it didn't seem to work so could u please fix this in a later update?

**Comment by blazejoski** [comment]
Which

> when it says "unknown", you didn't log into it yet. select the alt by clicking on it, then on the right press "login"

no it says failed to login

**Comment by 0x3C50** [comment]
are you sure you put in the right credentials
