### ISSUE TITLE
Sculk Spreading

### ISSUE THREAD

**Issue by Its1mpulse** [Coffee-Client/Coffee#34]
make command where if u have sculk catalyst sculk will spread from the catalyst as long as the command is running. command name should be like "spread" or "sculkspreader"

**Comment by RandomVersion** [comment]
0skar fan ^

**Comment by Its1mpulse** [comment]
yh

**Comment by 0x3C50** [comment]
![grafik](https://user-images.githubusercontent.com/99053360/179968537-96dece6a-cf4f-4b81-99a9-1ee8bd99c59a.png)
would this be adequate

**Comment by RandomVersion** [comment]
make it customizable
