### ISSUE TITLE
NBT

### ISSUE THREAD

**Issue by Its1mpulse** [Coffee-Client/Coffee#35]
Bring back all the shit from atomic to coffee. (screenshot below)
![image](https://user-images.githubusercontent.com/99086198/179212146-6916a2f7-c118-4f4a-b917-e877890b16c6.png)
![image](https://user-images.githubusercontent.com/99086198/179212172-ba86c42b-58c5-42dc-a0b5-a3eceb3640ad.png)
![image](https://user-images.githubusercontent.com/99086198/179212184-340146ae-f4db-4323-8d7f-264406ce8bb7.png)

they are very useful

**Comment by RandomVersion** [comment]
please

**Comment by RulyPancake** [comment]
from Atomic Private aswell 🙏

**Comment by RulyPancake** [comment]
ew why do I have that gay pfp on github

**Comment by fartdev** [comment]
im gui

**Comment by fartdev** [comment]
imgui made the jar really fat

**Comment by 0x3C50** [comment]
probably not going to implement all of them since most have been fixed but i am going to add some when i get to it
