### ISSUE TITLE
Add AntiInvalidAttributeCrash

### ISSUE THREAD

**Issue by Savvakos7** [Coffee-Client/Coffee#39]
Add it to anticrash so when you hover over an item with invalid attributes it doesn't crash your game.

**Comment by aaashleyyyy** [comment]
ninja from fortnite

> Add it to anticrash so when you hover over an item with invalid attributes it doesn't crash your game.

**Comment by RandomVersion** [comment]
show example nbt

**Comment by Savvakos7** [comment]
> show example nbt

It basically has invalid attributes and when you view it from your inv,you crash.

**Comment by 0x3C50** [comment]
you mean that salmon called "sam the salmon"?

**Comment by 0x3C50** [comment]
also known as "cole the cod"

**Comment by Savvakos7** [comment]
> you mean that salmon called "sam the salmon"?

I don't know what that is

**Comment by 0x3C50** [comment]
> > you mean that salmon called "sam the salmon"?
> 
> I don't know what that is

can i see an item with said "invalid attribute"

**Comment by Savvakos7** [comment]
> > > you mean that salmon called "sam the salmon"?
> > 
> > 
> > I don't know what that is
> 
> can i see an item with said "invalid attribute"

Join my server whenever you can and I'll show you

**Comment by RandomVersion** [comment]
bro its just an item :skull: 
it isnt a fucking 0day

**Comment by Savvakos7** [comment]
If it's not 0day then why doesn't your client have anticrash for it💀, better yet why are you asking for the NBT 💀,just give me your discord so you can fix this shit and don't make my life difficult

**Comment by RandomVersion** [comment]
you have brain damage

**Comment by 0x3C50** [comment]
turns out its not an invalid attribute, its just another common case of "ehehehe a lot to render = crash ehehehe"
ill add an option against it but there's at least a billion other "crashes" like this

**Comment by Savvakos7** [comment]
> you have brain damage

Big had block game hacker told me I have brain damage 😭

**Comment by RandomVersion** [comment]
because you do

**Comment by TaxEvasiqn** [comment]
real!

**Comment by Savvakos7** [comment]
> real!

"real!"🤓
