### ISSUE TITLE
Ore Simulator and Search

### ISSUE THREAD

**Issue by ViderOof** [Coffee-Client/Coffee#45]
The title. Ore Simulator uses the seed of the world to show you the ores on the map so it bypasses anti xray, and search just highlights blocks of your choosing.

**Comment by 0x3C50** [comment]
Oresim is a bit hard because I myself dont know how it works, maybe @19MisterX98 can help out in the future?

**Comment by 0x3C50** [comment]
It's on the bucket list, but it might be a while before it gets implemented, since I myself have no idea how seed simulation works
