### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by leev9** [Coffee-Client/Coffee#46]
can someone pls give me the lastest.jar for the 1.18 version the latest 1.18?
@0x3C50 @ac1dbitches @fartdev @aaashleyyyy

**Comment by 0x3C50** [comment]
no

**Comment by fartdev** [comment]
<img src="https://media.discordapp.net/attachments/904758037359759450/1004608386291208243/423a78a3de.gif" alt="ok haha">
