### ISSUE TITLE
all modules doubled and shitty fps as its TANKING my gpu. crypto miner?

### ISSUE THREAD

**Issue by OhFanix** [Coffee-Client/Coffee#49]
![image](https://user-images.githubusercontent.com/46995456/185098395-d7ff1be9-c982-42bc-8cf8-4c6bf15cd7e4.png)

**Comment by 0x3C50** [comment]
the client has a shit ton of rendering, especially the font takes a lot. what other mods do you have installed

**Comment by OhFanix** [comment]
no other mods

**Comment by 0x3C50** [comment]
Have you tried restarting the client

**Comment by OhFanix** [comment]
yes a few times
still the same issues of double rendering

**Comment by 0x3C50** [comment]
i dont see where the issue could be, which os and which game version are you running on? try downloading the latest dev jar and see if that one works

**Comment by 0x3C50** [comment]
lmk when you tried, ill reopen the issue
