### ISSUE TITLE
killaura "black hole" mode suggestion

### ISSUE THREAD

**Issue by Beta-51** [Coffee-Client/Coffee#57]
by looking at a player you want to bring towards you, and also assfuck them really hard (optional), you can add or subtract 180 to the yaw, and add or subtract 90 to the pitch, so you're facing away from the player, and then send attack packets to bring them towards you due to knockback and stuff. you could also use the velocity packet thing to control the strength of the knockback to a certain amount too.

this would be good for multiaura and just rolling around in an arena on a 1.8 based server, and just grabbing people and slowly killing them. in fact, it'd be hilarious.

**Comment by TaxEvasiqn** [comment]
im pretty sure kb is based on position relative to the entity rather than your rotation

**Comment by 0x3C50** [comment]
> im pretty sure kb is based on position relative to the entity rather than your rotation

yeah im pretty sure this wont work
