### ISSUE TITLE
.kill not working 

### ISSUE THREAD

**Issue by lNethunter** [Coffee-Client/Coffee#59]
it just gives me the egg,I can only.kill myself and the egg doesn't even disappear after

**Comment by 0x3C50** [comment]
is the person you're .killing in render distance

**Comment by 0x3C50** [comment]
> > is the person you're .killing in render distance
> 
> Yes

then vid please

**Comment by 0x3C50** [comment]
but i would like to see a vid of you trying it

**Comment by 0x3C50** [comment]
forgot to close this, the server apparently fixed it

**Comment by 0x3C50** [comment]
> > forgot to close this, the server apparently fixed it
> 
> Doesn't work on any server but alr

it did work when i tested it myself
