### ISSUE TITLE
make client more ghost?

### ISSUE THREAD

**Issue by erxson** [Coffee-Client/Coffee#6]
Add "Ghost mode" to client settings, which will:
move config folder to Documents,
hide hud on screenshots,
stop sending logs to console
if possible, download new fabric.mod.json and replace

**Comment by RandomVersion** [comment]
What about Linux

**Comment by erxson** [comment]
> What about Linux

user folder?

**Comment by RandomVersion** [comment]
💀

**Comment by 0x3C50** [comment]
going to be done in the near future
