### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AVuTuVA** [Coffee-Client/Coffee#61]
![image](https://user-images.githubusercontent.com/66278054/189303294-59bd1960-e35a-4386-b7c2-0e4d20d11ff6.png)

**Comment by 0x3C50** [comment]
Coffee is incompatible with lithium and will always be, Lithium modifies the entity collision detection along with coffee for NoPush, which is a feature neccessary for any client

**Comment by 0x3C50** [comment]
I did update the compatability just now but I can't test it, please download the latest dev build and tell me how it goes

**Comment by 0x3C50** [comment]
Download is [here](https://github.com/Coffee-Client/Coffee/suites/8210624884/artifacts/357769733)
