### ISSUE TITLE
buggy fading blocks

### ISSUE THREAD

**Issue by 0skar2** [Coffee-Client/Coffee#63]
https://user-images.githubusercontent.com/110235720/189899813-c903ed5a-621a-43ca-814c-e99486b4a63a.mp4

im not sure how to reproduce this, but it happens on server named play.kaboom.pw

**Comment by 0x3C50** [comment]
its the coordinates, does it happen with other types of rendering aswell?

**Comment by 0x3C50** [comment]
it does god fucking damnit

**Comment by 0x3C50** [comment]
and fixed, next push will have the fix
