### ISSUE TITLE
Add chat suggestions to your client and make it so it's openable on home screen 

### ISSUE THREAD

**Issue by lNethunter** [Coffee-Client/Coffee#64]

**Comment by 0x3C50** [comment]
Chat suggestions are already a thing, what do you mean with "making them openable on home screen"? If it is what i think it is, most of the commands wont work, since most are relying on being in a world

**Comment by 0x3C50** [comment]
I can't really make them usable on the home screen, since most use the world or other players, which dont exist in the home screen. Clickable is also kind of an issue, since I mixin into the chat screen, and can't easily add elements like I would with regular GUIs. I'll see what I can do tho

**Comment by 0x3C50** [comment]
Couldn't get it to work properly since most of the commands need a world to function properly, sorry
