### ISSUE TITLE
White screen ERROR

### ISSUE THREAD

**Issue by DesignAny** [Coffee-Client/Coffee#66]
FABRIC LOADER: 0.14.9 / 1.19.2
![obraz](https://user-images.githubusercontent.com/89824974/190875900-05246b62-d26d-4bcc-bb66-2371b8700b3a.png)

**Comment by 0x3C50** [comment]
are you using an amd gpu

**Comment by 0x3C50** [comment]
> yes

amd recently nuked half the opengl driver to make it "more performant", so a bunch of shit broke across a lot of programs for amd gpus. Can't really do much for it except disabling anti aliasing altogether, I might make an update in the future for that. For now, you're kind of locked out of coffee, sorry.
