### ISSUE TITLE
hudrenderer shit

### ISSUE THREAD

**Issue by 0skar2** [Coffee-Client/Coffee#72]
https://github.com/Coffee-Client/Coffee/blob/2145c99d8eeb73a2cbbc5cbbe9aca997da413367/src/main/java/coffee/client/feature/gui/hud/HudRenderer.java#L136

not sure what this code from line 136 to 153 is supposed to do,
it seems to only break it

**Comment by 0x3C50** [comment]
it scales the elements to the new window size if it changed

it does have a few funnies but it works overall so im gonna keep it
