### ISSUE TITLE
not compatible with lithium

### ISSUE THREAD

**Issue by GentlemanMC** [Coffee-Client/Coffee#75]
i traced the issue and its a mixin conflict at EntityMixin class

**Comment by GentlemanMC** [comment]
also btw the baritone jar ur using is outdated and only supports 1.19.1
so instead use this jar https://github.com/wagyourtail/baritone/commit/52d077de49b6bb2421f408df5fcf3e49e6fc106f

**Comment by 0x3C50** [comment]
known issue, wont fix
