### ISSUE TITLE
Lithium incompatibility/Fabric api breaking XRAY

### ISSUE THREAD

**Issue by Beta-51** [Coffee-Client/Coffee#8]
It crashes when used with lithium, and xray does not work with fabric api.
for the fabric api issue, you just need to change the way fabric api renders blocks.

**Comment by 0x3C50** [comment]
Same thing happens with inertia. Can't get to reproduce tho, send me a screenshot of how it looks when you try it

**Comment by RandomVersion** [comment]
ratio!!!

**Comment by Beta-51** [comment]
![image](https://user-images.githubusercontent.com/65312404/169703748-d0aedec1-b0f0-47cf-801c-5343e5c4102f.png)

**Comment by Beta-51** [comment]
just kinda looks like fullbright basically

**Comment by 0x3C50** [comment]
Needs more triage, can't get it to work for me. Closing for now
