### ISSUE TITLE
0x150 look at this it says you developed Ether client in this video: https://www.youtube.com/watch?v=3cje8XTNPGI&t=153s

### ISSUE THREAD

**Issue by CodeCat1500** [Coffee-Client/Coffee#84]

**Comment by CodeCat1500** [comment]
Look in the top left hand corner of the video at the beginning.

**Comment by 0x3C50** [comment]
seen it, I'll handle this

**Comment by CodeCat1500** [comment]
Okay if you get a download link it would mean a lot :)

**Comment by CodeCat1500** [comment]
@0x3C50

**Comment by CodeCat1500** [comment]
Oh an thank you for resolving the issue, those people on YouTube been driving me crazy past few days anyway
