### ISSUE TITLE
1.19.3 render bug

### ISSUE THREAD

**Issue by 0skar2** [Coffee-Client/Coffee#86]
getScreenSpaceCoordinate in renderer seems be broken

how to reproduce:
enable bowaimbot (with nearest crosshair mode)
try to aim (your hand is gonna dissapear and boxes wont render, also aiming is broken)

**Comment by 0x3C50** [comment]
Cant reproduce, can you send the game log?

**Comment by 0skar2** [comment]
your latest commit actually fixes that, so gonna close the issue
