### ISSUE TITLE
Bug: Air Jump - Kicked for flying

### ISSUE THREAD

**Issue by ShayBox** [Coffee-Client/Coffee#92]
If you spam Air Jump or enable No Jump Cooldown it will kick you for flying  
Can the Flight - Vanilla AC Bypass be added to Air Jump?

**Comment by ShayBox** [comment]
Similar bug: You will get kicked for flying if you enter freecam while flying

**Comment by 0x3C50** [comment]
seems like a skill issue, you need to drop down occasionally for the fall to register. adding the entire bypass to airjump would be overkill
